### PR TITLE
User/tvandewalle/themes

### PR DESCRIPTION
**Pull request by vdwtanner**
Adds themes to column mode for reskinning as your heart sees fit. Been sitting on this for a while, finally cleaned it up a wee bit and fixed a few bugs I was aware of.

* Fetching theme colors can be done using `ColumnMode::Theme`s, specifically `g_theme` in Program.cpp
  * Ex: `g_theme.GetColor(ColumnMode::THEME_COLOR::UI_PAPER)`
* Brushes are now cached in the `ColumnMode::BrushCache`, `g_brushCache`
  * Ex: `g_brushCache.GetBrush(/*color*/))`
  * Ex combined with theme fetch: `g_brushCache.GetBrush(g_theme.GetColor(ColumnMode::THEME_COLOR::UI_PAPER))`
  * Todo: cycle out unused brushes 
* Themes are stored at `%APPDATA%/ColumnMode/Themes` as json files with a .cmt extension. Opening one of these files for editing sets it as the current theme and gives more or less real time updates as you change that data.
  * Added a JSON header library to enable this. Not sure if it's the best option out there, but it gets the job done and opens up some doors for user settings (would love to save default plugins to load, theme preference, etc)
  * This also required the addition of some new code to listen for when a user has stopped typing. Currently this has the clunky working name `ConfirmEdits`, but should probably be something like `OnUserStoppedTyping`... Open to suggestions :) It's also all done on the UI thread which is unfortunate, but it looks like the code to try to offload that is on a different machine and has issues anyway. For now this is "fast enough™️" for what it needs to do and doesn't cause the app to crash.
* Creating a new theme will give you default settings to work with

### CODE REVIEW

**Comment by clandrew** [comment]
In the future could you consider using a branch instead of a fork? If it's no difference to you. The workflow is a bit more convenient for me.

**Comment by clandrew** [comment]
Small suggestion: add a separator between the two checkable options and 'Themes'. Currently a bit subtle that the first two are radiobuttoned to each other and the third item is a separate thing
image

**Comment by clandrew** [comment]
If we're gonna have custom themes driven by user-editable text files, could we have documented somewhere what these are? Some are more obvious than others 
image

**Comment by clandrew** [comment]
If you do the following
1. Create a custom theme
2. Put some term like 'asdf' for one of the color values
3. ColumnMode will silently not load it. It would be a bit better if there was some kind of error message explaining that it wasn't loaded

This is the only thing a bit blocking (if you don't want to get to it i'll do it) the rest looks good

**Comment by vdwtanner** [comment]
@clandrew would you be ok with merging it as is now, and then I'll apply the fixes as a branch of your repo instead of on the fork?  I think I want to try using some of the new stuff added in this PR (specifically the ability to take an action based on when the user stops typing) during WoL next week.

**Comment by clandrew** [comment]
> would you be ok with merging it as is now, and then I'll apply the fixes as a branch of your repo instead of on the fork? I think I want to try using some of the new stuff added in this PR (specifically the ability to take an action based on when the user stops typing) during WoL next week.

Sure! That's a good plan :)

**Pull request merged**
